### ISSUE TITLE
Feature Requests - Cavalry Bases & Magenet Insets

### ISSUE THREAD

**Issue by DaytonEclipse** [eljeko/Parametric-OpenScad-movement-tray-generator#1]
Hey, 

First off this is brilliant and works like a charm.  I'm going to be printing some starting tomorrow to rank up my gobbos & dwarves.

I have a couplle of features requests to run by you and see if they could in any way be accomodated.

1) Cavalry bases will undergo similar resizings with 25x50 becoming 30x60.  Is it possible to get a version to cover cavalry?  Also asking if the cavalry one could allow from straight ranking or the tapered style like this:
      [GS World 180x90mm](https://www.greenstuffworld.com/en/warhammer-old-world-bases/3422-mdf-movement-trays-old-world-180x90mm-1x2x3.html)

2) Is it possible to include a parameter than enables the inset of a magnet in the centre of each troop hole to allow for magnetisation.  The goto magnet seems to be 3x1mm's, but a parameter that could allow for different sizes would be awesome..

Thanks for considering and understand if you're not able to accomodate.

**Comment by eljeko** [comment]
Thank you for feedback and for request

I'm coding to support Cavalry tray generation.
The lance formation (for Brets) would be a bit tricky to implement, ill'try in the future (i create an issue to track).
The insets for magnets could be easily implemented, I'll work on it (i create an issue to track).

**Comment by eljeko** [comment]
@DaytonEclipse I close this for now, if you want please follow the three different issues I opened.

Thank you

**Comment by DaytonEclipse** [comment]
Thank you so much for considering and then actioning these.  Amazing work!
