### ISSUE TITLE
Option to add rear wall on empty movment tray

### ISSUE THREAD

**Issue by pwojewodzic** [eljeko/Parametric-OpenScad-movement-tray-generator#11]
There is an option to generate also rear wall on empty movment trays?

![image](https://github.com/eljeko/Parametric-OpenScad-movement-tray-generator/assets/24620458/71eaa3c8-e97f-4050-9054-d7099c3c5ecf)

**Comment by mwstewart85** [comment]
I would also be keen on keeping the back wall during generation.

**Comment by natep-tech** [comment]
I am also interested in this feature
