### ISSUE TITLE
Shorten slots in parametric base generator

### ISSUE THREAD

**Issue by davidhopkinson26** [eljeko/Parametric-OpenScad-movement-tray-generator#14]
What?
It would be really handy to be able to adjust the length of slots in parametric base generator in the same way as width. 

Why?
This would allow creation of a shorter slot which matches the base stub of models previously based on smaller base sizes before TOW for easier rebasing.

How?
Add a new user assignable parameter for slotta x dimension and modify slotta module to account for this.  Happy to submit a PR with my local fix if contributions welcome.  Names don't make sense without changes so I went for renaming slotta_width to slotta_depth and calling the new parameter slotta_width.

**Comment by eljeko** [comment]
More than happy to receive a PR!

Just a note: I struggled a bit to adjust the proportion and location of the slotta for diagonal placement so I kindly ask if you can test well it before submitting PR.

**Comment by davidhopkinson26** [comment]
Thanks for the note, I did not look at diagonal slots. Will have a go at making this work.
