### ISSUE TITLE
Support for magnets corners location

### ISSUE THREAD

**Issue by eljeko** [eljeko/Parametric-OpenScad-movement-tray-generator#8]
Support for magnets corners location:

```
+-----------+
| O       O |
|           |
|           |
| O       O |
+-----------+
```

**Comment by DaytonEclipse** [comment]
Would it be possible to have a parameter cover placement, so for example:

1 - Centre
2 - Top and bottom middle
4 - Corners
5 - Corners & Middle
6 - Corners & Middle sides
7 - Corners, Middle Sides and centre
9 - Corners, Middles & Centre.

This would be invaluable as you magnetise the bigger bases, but if not then an option 2 for infantry would be super useful.

Example 1 - Centre
```
+-----------+
|           |
|           |
|     O     |
|           |
|           |
+-----------+

```
Example 2 - Top & Bottom Middle
```
+-----------+
|     O     |
|           |
|           |
|           |
|     O     |
+-----------+
```

Example 4 - Corners
```
+-----------+
| O       O |
|           |
|           |
|           |
| O       O |
+-----------+

```
Example 5 - Corners & Middle
```
+-----------+
| O       O |
|           |
|     O     |
|           |
| O       O |
+-----------+
```

Example 6 - Corners & Middle Sides

```
+-----------+
| O       O |
|           |
| O       O |
|           |
| O       O |
+-----------+
```

Example 7 - Corners, Middlew Sides & Centre

```
+-----------+
| O       O |
|           |
| O   O   O |
|           |
| O       O |
+-----------+
```

Example 9 - Middle Top & Bottom, Middle Sides & Centre.

```
+-----------+
| O   O   O |
|           |
| O   O   O |
|           |
| O   O   O |
+-----------+
```
